name: Daily Glass Tasks Notification

on:
  schedule:
    - cron: '0 12 * * *' # Her gün saat 12:00'de çalıştır

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Send Glass tasks notification
      run: python ./.github/scripts/send_glass_tasks_notification.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
