name: Send Glass Tasks Email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 00:00 UTC

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gql
      
      - name: Get last 3 tasks
        run: |
          python .github/scripts/send_glass_tasks_email.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
