name: Send Glass Tasks Email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gql
      
      - name: Get last 3 tasks
        run: |
          python .github/scripts/send_glass_tasks_email.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
