name: Test1


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gql
      
      - name: Get last 3 tasks
        run: |
          python .github/scripts/send_glass_tasks_email.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
